import type { CEFRLevel } from './resources';

export interface WritingPrompt {
  id: string;
  level: CEFRLevel;
  topic: string;
  prompt: string;
  promptEn: string;
  hints?: string[];
  wordCountTarget: number;
}

export const WRITING_PROMPTS: WritingPrompt[] = [
  // A1
  {
    id: 'a1-1',
    level: 'A1',
    topic: 'Introduksjon',
    prompt: 'Skriv om deg selv. Hva heter du? Hvor gammel er du? Hvor bor du?',
    promptEn: 'Write about yourself. What is your name? How old are you? Where do you live?',
    hints: ['Jeg heter...', 'Jeg er ... år gammel', 'Jeg bor i...'],
    wordCountTarget: 40,
  },
  {
    id: 'a1-2',
    level: 'A1',
    topic: 'Familie',
    prompt: 'Beskriv familien din. Hvor mange er dere? Hva heter de?',
    promptEn: 'Describe your family. How many are you? What are their names?',
    hints: ['Familien min har...', 'broren min / søsteren min', 'moren min / faren min'],
    wordCountTarget: 50,
  },
  {
    id: 'a1-3',
    level: 'A1',
    topic: 'Mat',
    prompt: 'Hva liker du å spise? Hva er favorittmaten din?',
    promptEn: 'What do you like to eat? What is your favourite food?',
    hints: ['Jeg liker å spise...', 'Favorittmaten min er...', 'Jeg liker ikke...'],
    wordCountTarget: 40,
  },
  {
    id: 'a1-4',
    level: 'A1',
    topic: 'Daglig rutine',
    prompt: 'Beskriv en vanlig dag. Hva gjør du om morgenen, om ettermiddagen og om kvelden?',
    promptEn: 'Describe an ordinary day. What do you do in the morning, afternoon, and evening?',
    hints: ['Jeg står opp klokka...', 'Så spiser jeg...', 'Om kvelden...'],
    wordCountTarget: 60,
  },
  {
    id: 'a1-5',
    level: 'A1',
    topic: 'Klær',
    prompt: 'Hva har du på deg i dag? Beskriv klærne dine. Hvilken farge er de?',
    promptEn: 'What are you wearing today? Describe your clothes. What colour are they?',
    hints: ['Jeg har på meg...', 'en rød/blå/grønn...', 'bukser, genser, jakke, sko'],
    wordCountTarget: 40,
  },
  {
    id: 'a1-6',
    level: 'A1',
    topic: 'Dyr',
    prompt: 'Har du et kjæledyr? Hva er favorittdyret ditt? Beskriv det.',
    promptEn: 'Do you have a pet? What is your favourite animal? Describe it.',
    hints: ['Jeg har en...', 'Det er...', 'stor/liten, søt, morsom'],
    wordCountTarget: 40,
  },
  {
    id: 'a1-7',
    level: 'A1',
    topic: 'Hjemmet',
    prompt: 'Beskriv hjemmet ditt. Hvilke rom har du? Hva er favorittrommet ditt?',
    promptEn: 'Describe your home. What rooms do you have? What is your favourite room?',
    hints: ['Jeg bor i en...', 'Hjemmet mitt har...', 'stue, kjøkken, soverom, bad'],
    wordCountTarget: 50,
  },
  {
    id: 'a1-8',
    level: 'A1',
    topic: 'Tall og handel',
    prompt: 'Hva kjøper du vanligvis i butikken? Skriv om en handletur. Hva koster ting?',
    promptEn: 'What do you usually buy at the shop? Write about a shopping trip. How much do things cost?',
    hints: ['Jeg kjøper...', 'Det koster...', 'kroner, melk, brød, epler'],
    wordCountTarget: 50,
  },
  {
    id: 'a1-9',
    level: 'A1',
    topic: 'Transport',
    prompt: 'Hvordan kommer du deg til jobb eller skole? Beskriv reisen din.',
    promptEn: 'How do you get to work or school? Describe your journey.',
    hints: ['Jeg tar...', 'buss, tog, sykkel, bil', 'Det tar ... minutter'],
    wordCountTarget: 40,
  },
  {
    id: 'a1-10',
    level: 'A1',
    topic: 'Farger',
    prompt: 'Hva er favorittfargen din? Beskriv tre ting i favorittfargen din.',
    promptEn: 'What is your favourite colour? Describe three things in your favourite colour.',
    hints: ['Favorittfargen min er...', 'en ... bil', 'himmelen er...'],
    wordCountTarget: 40,
  },
  // A2
  {
    id: 'a2-1',
    level: 'A2',
    topic: 'Helgen',
    prompt: 'Hva gjorde du i helgen? Beskriv minst tre ting du gjorde.',
    promptEn: 'What did you do this weekend? Describe at least three things you did.',
    hints: ['I helgen...', 'På lørdag...', 'Etterpå...', 'preteritum: gikk, så, spiste'],
    wordCountTarget: 80,
  },
  {
    id: 'a2-2',
    level: 'A2',
    topic: 'Bosted',
    prompt: 'Beskriv stedet du bor. Hva er fint der? Hva kan man gjøre der?',
    promptEn: 'Describe the place where you live. What is nice there? What can you do there?',
    hints: ['Jeg bor i...', 'Det er et ... sted', 'Man kan...', 'I nærheten av...'],
    wordCountTarget: 100,
  },
  {
    id: 'a2-3',
    level: 'A2',
    topic: 'Hobbyer',
    prompt: 'Skriv om hobbyene dine. Hva liker du å gjøre på fritiden? Hvorfor?',
    promptEn: 'Write about your hobbies. What do you like to do in your free time? Why?',
    hints: ['På fritiden liker jeg...', 'Det er gøy fordi...', 'Jeg pleier å...'],
    wordCountTarget: 100,
  },
  {
    id: 'a2-4',
    level: 'A2',
    topic: 'Vær og årstider',
    prompt: 'Hva er favorittårstiden din? Beskriv været og hva du liker å gjøre da.',
    promptEn: 'What is your favourite season? Describe the weather and what you like to do then.',
    hints: ['Favorittårstiden min er...', 'Da er det...', 'Jeg liker å... når det er...'],
    wordCountTarget: 100,
  },
  {
    id: 'a2-5',
    level: 'A2',
    topic: 'Favorittfilm',
    prompt: 'Hva er favorittfilmen eller -serien din? Beskriv den kort. Hvorfor liker du den?',
    promptEn: 'What is your favourite film or series? Describe it briefly. Why do you like it?',
    hints: ['Favorittfilmen min er...', 'Historien handler om...', 'Jeg liker den fordi...'],
    wordCountTarget: 100,
  },
  {
    id: 'a2-6',
    level: 'A2',
    topic: 'Venner',
    prompt: 'Beskriv en god venn. Hvordan møttes dere? Hva liker dere å gjøre sammen?',
    promptEn: 'Describe a good friend. How did you meet? What do you like to do together?',
    hints: ['Bestevennen min heter...', 'Vi møttes...', 'Sammen liker vi å...'],
    wordCountTarget: 100,
  },
  {
    id: 'a2-7',
    level: 'A2',
    topic: 'Jobb eller skole',
    prompt: 'Beskriv jobben eller skolen din. Hva gjør du der? Hva liker du best?',
    promptEn: 'Describe your job or school. What do you do there? What do you like best?',
    hints: ['Jeg jobber som... / Jeg går på...', 'Jeg pleier å...', 'Det beste er...'],
    wordCountTarget: 100,
  },
  {
    id: 'a2-8',
    level: 'A2',
    topic: 'Sport',
    prompt: 'Driver du med sport? Hva er den mest populære sporten i ditt land? Liker du å se på sport?',
    promptEn: 'Do you do sports? What is the most popular sport in your country? Do you like watching sports?',
    hints: ['Jeg spiller / driver med...', 'Den mest populære...', 'Jeg ser på...'],
    wordCountTarget: 100,
  },
  {
    id: 'a2-9',
    level: 'A2',
    topic: 'Et minneverdig måltid',
    prompt: 'Beskriv et godt måltid du husker. Hva spiste du? Hvem var du med? Hvor var du?',
    promptEn: 'Describe a good meal you remember. What did you eat? Who were you with? Where were you?',
    hints: ['En gang spiste jeg...', 'Jeg var med...', 'Det smakte...'],
    wordCountTarget: 100,
  },
  {
    id: 'a2-10',
    level: 'A2',
    topic: 'Musikk',
    prompt: 'Hva slags musikk liker du? Har du en favorittartist eller et favorittband? Beskriv musikken.',
    promptEn: 'What kind of music do you like? Do you have a favourite artist or band? Describe the music.',
    hints: ['Jeg liker...', 'Favorittartisten min er...', 'Musikken er...'],
    wordCountTarget: 100,
  },
  {
    id: 'a2-11',
    level: 'A2',
    topic: 'Barndom',
    prompt: 'Beskriv en god hukommelse fra barndommen. Hva skjedde? Hvem var med?',
    promptEn: 'Describe a good memory from your childhood. What happened? Who was there?',
    hints: ['Da jeg var liten...', 'En gang...', 'Jeg husker at...'],
    wordCountTarget: 120,
  },
  {
    id: 'a2-12',
    level: 'A2',
    topic: 'Drømmeferie',
    prompt: 'Beskriv drømmeferien din. Hvor vil du reise? Hva vil du gjøre der?',
    promptEn: 'Describe your dream holiday. Where would you travel? What would you do there?',
    hints: ['Drømmeferien min er...', 'Jeg vil reise til...', 'Der vil jeg...'],
    wordCountTarget: 100,
  },
  // B1
  {
    id: 'b1-1',
    level: 'B1',
    topic: 'Norsk mat',
    prompt: 'Hva synes du om norsk mat? Har du smakt noen norske retter? Sammenlign med maten fra ditt eget land.',
    promptEn: 'What do you think about Norwegian food? Have you tasted any Norwegian dishes? Compare with food from your own country.',
    hints: ['Jeg synes at...', 'Sammenlignet med...', 'brunost, fårikål, lutefisk, kjøttkaker'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-2',
    level: 'B1',
    topic: 'Reise',
    prompt: 'Skriv om en reise du har vært på. Hvor reiste du? Hva opplevde du? Hva var det beste?',
    promptEn: 'Write about a trip you have taken. Where did you travel? What did you experience? What was the best part?',
    hints: ['Jeg reiste til...', 'Det mest spennende var...', 'Jeg anbefaler...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-3',
    level: 'B1',
    topic: 'Å lære norsk',
    prompt: 'Hvorfor lærer du norsk? Hva er det vanskeligste med norsk? Hva gjør du for å øve?',
    promptEn: 'Why are you learning Norwegian? What is the hardest part about Norwegian? What do you do to practice?',
    hints: ['Grunnen til at...', 'Det vanskeligste er...', 'For å forbedre meg...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-4',
    level: 'B1',
    topic: 'Teknologi',
    prompt: 'Hvordan bruker du teknologi i hverdagen? Synes du vi bruker for mye tid på skjerm?',
    promptEn: 'How do you use technology in everyday life? Do you think we spend too much time on screens?',
    hints: ['I hverdagen bruker jeg...', 'På den ene siden...', 'På den andre siden...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-5',
    level: 'B1',
    topic: 'Sosiale medier',
    prompt: 'Hvordan bruker du sosiale medier? Synes du de har mer positive eller negative effekter på samfunnet?',
    promptEn: 'How do you use social media? Do you think they have more positive or negative effects on society?',
    hints: ['Jeg bruker ... for å...', 'En positiv effekt er...', 'Men jeg bekymrer meg for...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-6',
    level: 'B1',
    topic: 'Norsk natur',
    prompt: 'Hva vet du om norsk natur? Hva er friluftsliv? Liker du å være ute i naturen?',
    promptEn: 'What do you know about Norwegian nature? What is "friluftsliv"? Do you like being out in nature?',
    hints: ['Norsk natur er kjent for...', 'Friluftsliv betyr...', 'Jeg liker / liker ikke å...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-7',
    level: 'B1',
    topic: '17. mai',
    prompt: 'Hva vet du om 17. mai i Norge? Sammenlign med nasjonaldagen i ditt hjemland.',
    promptEn: 'What do you know about 17 May in Norway? Compare with the national day in your home country.',
    hints: ['Den norske nasjonaldagen...', 'Man pleier å...', 'I hjemlandet mitt feirer vi...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-8',
    level: 'B1',
    topic: 'Helse og trening',
    prompt: 'Hva gjør du for å holde deg frisk? Er du flink til å trene og spise sunt? Hva er vanskelig?',
    promptEn: 'What do you do to stay healthy? Are you good at exercising and eating well? What is difficult?',
    hints: ['For å holde meg frisk...', 'Jeg prøver å...', 'Det vanskeligste er...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-9',
    level: 'B1',
    topic: 'Drømmejobb',
    prompt: 'Hva er drømmejobben din? Hva må man gjøre for å få den jobben? Har drømmene dine endret seg?',
    promptEn: 'What is your dream job? What do you need to do to get that job? Have your dreams changed?',
    hints: ['Drømmejobben min er...', 'For å bli... må man...', 'Da jeg var ung...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-10',
    level: 'B1',
    topic: 'En bok du liker',
    prompt: 'Beskriv en bok du har likt. Hva handler den om? Hvem anbefaler du den til, og hvorfor?',
    promptEn: 'Describe a book you have enjoyed. What is it about? Who do you recommend it to, and why?',
    hints: ['Boken jeg vil anbefale heter...', 'Den handler om...', 'Jeg anbefaler den til alle som...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-11',
    level: 'B1',
    topic: 'Kollektivtransport',
    prompt: 'Hva synes du om kollektivtransporten der du bor? Er det bedre å bruke bil eller offentlig transport?',
    promptEn: 'What do you think of public transport where you live? Is it better to use a car or public transport?',
    hints: ['Kollektivtransporten her er...', 'En fordel med buss/tog er...', 'Ulempen med bil er...'],
    wordCountTarget: 150,
  },
  {
    id: 'b1-12',
    level: 'B1',
    topic: 'Frivillighet',
    prompt: 'Har du noen gang jobbet frivillig? Hva synes du om frivillighetsarbeid? Hva ville du gjort?',
    promptEn: 'Have you ever volunteered? What do you think about volunteer work? What would you do?',
    hints: ['Jeg har / har aldri...', 'Frivillighetsarbeid er viktig fordi...', 'Hvis jeg skulle...'],
    wordCountTarget: 150,
  },
  // B2
  {
    id: 'b2-1',
    level: 'B2',
    topic: 'Hjemmekontor',
    prompt: 'Diskuter fordeler og ulemper med hjemmekontor. Hva foretrekker du, og hvorfor?',
    promptEn: 'Discuss the advantages and disadvantages of working from home. What do you prefer, and why?',
    hints: ['En fordel er at...', 'En ulempe er at...', 'Etter min mening...', 'fleksibilitet, produktivitet, sosialt'],
    wordCountTarget: 250,
  },
  {
    id: 'b2-2',
    level: 'B2',
    topic: 'Miljø',
    prompt: 'Hva kan vi gjøre for å ta bedre vare på miljøet? Diskuter hva enkeltpersoner og samfunnet kan bidra med.',
    promptEn: 'What can we do to take better care of the environment? Discuss what individuals and society can contribute.',
    hints: ['Det er viktig at...', 'For det første...', 'Dessuten...', 'klimaendringer, bærekraftig, utslipp'],
    wordCountTarget: 250,
  },
  {
    id: 'b2-3',
    level: 'B2',
    topic: 'Kultur',
    prompt: 'Sammenlign norsk kultur med kulturen i ditt hjemland. Hva er de største forskjellene? Hva overrasket deg mest?',
    promptEn: 'Compare Norwegian culture with the culture in your home country. What are the biggest differences? What surprised you the most?',
    hints: ['Den største forskjellen er...', 'I motsetning til...', 'Det som overrasket meg...', 'janteloven, friluftsliv, likestilling'],
    wordCountTarget: 250,
  },
  {
    id: 'b2-4',
    level: 'B2',
    topic: 'Innvandring',
    prompt: 'Diskuter innvandring i Norge. Hvilke utfordringer og muligheter bringer det med seg? Hva er viktig for god integrering?',
    promptEn: 'Discuss immigration in Norway. What challenges and opportunities does it bring? What is important for good integration?',
    hints: ['Et viktig aspekt er...', 'Man bør ta hensyn til...', 'integrering, mangfold, språkopplæring'],
    wordCountTarget: 300,
  },
  {
    id: 'b2-5',
    level: 'B2',
    topic: 'Velferdsstaten',
    prompt: 'Hva kjennetegner den norske velferdsstaten? Diskuter fordeler og utfordringer ved en slik modell i fremtiden.',
    promptEn: 'What characterises the Norwegian welfare state? Discuss the advantages and challenges of such a model in the future.',
    hints: ['Den norske modellen bygger på...', 'En sentral fordel er...', 'En utfordring er...', 'NAV, trygd, offentlige tjenester'],
    wordCountTarget: 300,
  },
  {
    id: 'b2-6',
    level: 'B2',
    topic: 'Kunstig intelligens',
    prompt: 'Hvilken innvirkning har kunstig intelligens på arbeidslivet og samfunnet? Ser du mest muligheter eller trusler?',
    promptEn: 'What impact does artificial intelligence have on working life and society? Do you see mostly opportunities or threats?',
    hints: ['KI kan føre til...', 'En reell fare er...', 'Det er likevel viktig å huske at...', 'automatisering, kreativitet, personvern'],
    wordCountTarget: 300,
  },
  {
    id: 'b2-7',
    level: 'B2',
    topic: 'By og land',
    prompt: 'Er det bedre å bo i en storby eller på landet? Diskuter livskvalitet, muligheter og utfordringer begge steder.',
    promptEn: 'Is it better to live in a big city or in the countryside? Discuss quality of life, opportunities, and challenges in both places.',
    hints: ['Storbyen tilbyr...', 'På landet er det...', 'Livskvalitet handler om...', 'tilbud, natur, trygghet, tempo'],
    wordCountTarget: 280,
  },
  {
    id: 'b2-8',
    level: 'B2',
    topic: 'Psykisk helse',
    prompt: 'Psykisk helse er et stadig viktigere tema. Hva tror du er årsaken til økt psykisk uhelse, særlig blant unge? Hva kan gjøres?',
    promptEn: 'Mental health is an increasingly important topic. What do you think causes increased mental illness, especially among young people? What can be done?',
    hints: ['En mulig forklaring er...', 'Forskning viser at...', 'Samfunnet bør...', 'press, ensomhet, skjermtid, stigma'],
    wordCountTarget: 300,
  },
  {
    id: 'b2-9',
    level: 'B2',
    topic: 'Likestilling',
    prompt: 'Norge regnes som et av verdens mest likestilte land. Hva har bidratt til dette? Er det fortsatt utfordringer igjen?',
    promptEn: 'Norway is considered one of the world\'s most equal countries. What has contributed to this? Are there still challenges remaining?',
    hints: ['Likestilling i Norge er...', 'Historisk sett har...', 'Til tross for fremgang...', 'foreldrepermisjon, lønnsgap, representasjon'],
    wordCountTarget: 300,
  },
  {
    id: 'b2-10',
    level: 'B2',
    topic: 'Klimapolitikk',
    prompt: 'Hva bør Norge gjøre for å bekjempe klimaendringer? Diskuter spenningen mellom oljeindustrien og klimamålene.',
    promptEn: 'What should Norway do to combat climate change? Discuss the tension between the oil industry and climate targets.',
    hints: ['På den ene siden...', 'Paradokset er at...', 'En langsiktig løsning er...', 'Parisavtalen, oljefond, fornybar energi'],
    wordCountTarget: 300,
  },
  {
    id: 'b2-11',
    level: 'B2',
    topic: 'Norsk identitet',
    prompt: 'Hva vil det si å være norsk i dag? Har globaliseringen endret den norske identiteten? Diskuter.',
    promptEn: 'What does it mean to be Norwegian today? Has globalisation changed Norwegian identity? Discuss.',
    hints: ['Tradisjonelt har nordmenn vært...', 'Globalisering har ført til...', 'Spørsmålet er om...', 'friluftsliv, janteloven, dugnad, mangfold'],
    wordCountTarget: 280,
  },
  {
    id: 'b2-12',
    level: 'B2',
    topic: 'Work-life balance',
    prompt: 'Nordmenn er kjent for god balanse mellom arbeid og fritid. Hva tror du er grunnene til dette, og hva kan andre land lære av Norge?',
    promptEn: 'Norwegians are known for a good work-life balance. What do you think are the reasons for this, and what can other countries learn from Norway?',
    hints: ['En viktig faktor er...', 'I mange andre land...', 'Forskning viser at...', 'fleksibel arbeidstid, ferie, tillit, produktivitet'],
    wordCountTarget: 300,
  },
];
